language: node_js

#services:
#  - postgresql

node_js:
 - "8"

#before_script:
#  - psql -c 'drop database if exists travis;' -U postgres
#  - psql -c 'create database travis;' -U postgres

before_install:
  - npm install -g mocha
  - npm install

script:
 - npm run test

after_success:
 - npm run coverage
