language: node_js

node_js:
 - "8.11.1"

before_install:
- npm install -g mocha
- npm install -g coveralls
- npm install -g mocha-lcov-reporter
- npm install -g jscoverage

before_script:
 - npm install

script:
 - npm run test

after_success:
- npm run coverage
