language: node_js

node_js:
 - "8.11.1"

before_install:
- npm install -g mocha

before_script:
 - npm install

script:
 - npm run test

after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha --require babel-register api/tests/ -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
