language: node_js

services:
  - postgresql

node_js:
 - "stable"

before_install:
#  - npm install -g mocha
  - npm install

before_script:
  - psql -c 'create database travis_test;' -U postgres

script:
 - npm test

after_success:
 - npm run coverage
